name: Repository dispatch run

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch or PR Base
        id: branch_info
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
            echo "REPOSITORY_NAME=${{ github.event.pull_request.base.full_name }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "REPOSITORY_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          fi

      - name: Curl API
        run: |
          TOKEN=${{ secrets.MY_PAT }}
          OWNER=${{ secrets.OWNER }}
          REPO=${{ secrets.TARGET_REPO }}
          BRANCH=${{ env.BRANCH_NAME }}
          REPOSITORY=${{ env.REPOSITORY_NAME }}

          curl \
            -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d "{\"event_type\":\"on-demand-test\",\"client_payload\":{\"ref\":\"$BRANCH\",\"repo\":\"$REPOSITORY\"}}"
