name: Repository dispatch run

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch or PR Base
        id: branch_info
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Print Send Data
        run: |
          echo "Send Event Data:"
          echo "Branch: ${{ env.BRANCH_NAME }}"
          echo "Repo: ${{ env.REPOSITORY_NAME }}"

      - name: Curl API
        run: |
          OWNER=takanotaiga
          REPO=b
          BRANCH=${{ env.BRANCH_NAME }}
          REPOSITORY=${{ env.REPOSITORY_NAME }}

          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d "{\"event_type\":\"on-demand-test\",\"client_payload\":{\"ref\":\"$BRANCH\",\"repo\":\"$REPOSITORY\"}}"
